version: "3.8"
services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        stop_signal: SIGINT
        # Замените на "always" или "on-failure", чтобы контейнер автоматически пересоздавался
        restart: "no"
        env_file:
            - .env
        depends_on:
            - grafana
            - influxdb

    influxdb:
        image: influxdb:1.8-alpine
        # Необходимо в первый раз задать контейнеру имя, чтобы проще было подключаться из терминала
        # Далее можно убрать следующую строку
        container_name: "first-influxdb"
        # Замените на "always" или "on-failure", чтобы контейнер автоматически пересоздавался
        restart: "no"
        volumes:
            - "/path/to/your/influxdb_data:/var/lib/influxdb"
        env_file:
            - .env

    grafana:
        image: grafana/grafana:8.2.1
        # Замените на "always" или "on-failure", чтобы контейнер автоматически пересоздавался
        restart: "no"
        volumes:
            - "/path/to/your/grafana_data:/var/lib/grafana"
        environment:
            - GF_DATE_FORMATS_DEFAULT_TIMEZONE=browser
        # Если нужно на хосте просматривать данные или прокинуть наружу
        ports:
            - "3000:3000"
